# Generated by Django 5.2.13 on 2026-04-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0004_doctorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabplan',
            name='weekly_goal',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
